name: Code quality

on: 
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  windows: 
    name: Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v7
      - name: Enable long paths on Windows
        run: git config --system core.longpaths true
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v3
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Type check
        run: pnpm typecheck
      - name: Lint check
        run: pnpm lint
      - name: Build
        run: pnpm build:win