name: Code quality

on: 
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  windows: 
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Type check
        run: npm run typecheck
      - name: Lint check
        run: npm run lint
      - name: Build
        run: npm run build:win